services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: storeapi_db
      POSTGRES_USER: storeapi_user
      POSTGRES_PASSWORD: storeapi_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  storeapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__PostgresDb: "Host=db;Database=storeapi_db;Username=storeapi_user;Password=storeapi_pass"

volumes:
  postgres_data:
  rabbitmq_data:
